### ISSUE TITLE
A variety of evaluation functions

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#320] opened 2017-05-19 04:36 UTC
Once you get a basic example of evolution working in the microRTS game, we can start thinking about a variety of different evaluation functions. Specifically, we should probably turn the existing NN eval class into an abstract base class that is extended by several variants, such as the ones I wrote on the white board:
1) One like what you already have, that just counts unit types.
2) One that has one input per board square, essentially assigning a score to each type of unit.
3) One that has multiple board sized input spaces, each for different classes of units.

**Comment by alicequint** [comment] 2017-05-19 19:59
1. done!
2. started but not finished,
3. not started

**Comment by schrum2** [comment] 2017-05-23 01:37
It seems like we'll end up with several evaluation functions, so move them into a package called:
edu.utexas.cs.nn.tasks.microrts.evaluationfunctions

**Comment by alicequint** [comment] 2017-05-25 20:10
1. done
2. done 
3. started but not finished

**Comment by schrum2** [comment] 2017-05-29 16:59
It sounds like the complex eval function will be influenced by various command line parameters that turn groups of input options on/off. Each of these groups of inputs should also be associated with a HyperNEAT input substrate

**Comment by alicequint** [comment] 2017-06-12 21:58
all of the easy methods in complex eval function are done, including gameStateToArray, although for it to work i need to complete the implementation of another method called populateSubstrates, which takes a unit, the array, and some information about the substrate sizes etc and represents the unit in the appropriate place in the array, depending on the command line parameter

**Comment by alicequint** [comment] 2017-06-19 21:43
there is a nightmarish bug in complexEvalFunction
adding units to substrates works for all units Except mobile units, where, depending on the agent, it either starts fine but then loses accuracy when compared to the gs visualizer or never represents the game state to begin with.
for example, the initial pgs contains units located at spaces 1,1 and 6,6, but in the most recent trial i did, there were "workers" at 0,1, 4,5, and 6,6.
these 'workers' seem to be objects returned by pgs.getUnitAt();
they do not move in predictable patterns, there is not always the same number of them from moment to moment, and they never seem to affect the game state, so thats why i think that the problem is here instead of in the visualizer.

**Comment by schrum2** [comment] 2017-06-20 01:34
Not a bug. See my commit message above, and feel free to remove (or maybe just comment out) all of your print statements.

**Comment by alicequint** [comment] 2017-06-20 20:42
complex eval function works now! by default it mimics behavior of nn2dEvalFunction, but parameters can be changed to configure multiple substrates differently.
it has not been tested thoroughly but preliminary runs seem to indicate that it does everything that it was meant to do.
the only outstanding issue with it left is that smudging for larger maps is yet to be implemented, but that is a part of #341 so im closing this issue now.

**Comment by schrum2** [comment] 2017-06-26 17:44
I've re-opened this so that you can track the refactoring of this code into separate substrate classes.

**Comment by schrum2** [comment] 2017-06-26 21:32
MicroRTSSubstrateInputs and its child classes should be moved to a new package:
edu.utexas.cs.nn.tasks.microrts.evaluation.inputsubstrates

**Comment by alicequint** [comment] 2017-06-29 16:16
moved substrates to their own package, [...]microRTS.evaluation.substrates

**Closed as completed by alicequint** 2017-06-29 16:16 UTC
Labels: complete before end of SCOPE, MicroRTS
