### ISSUE TITLE
fix null pointers for post eval in predprey

### ISSUE THREAD

**Issue by Rollinsa** [schrum2/MM-NEATv2#48] opened 2016-05-12 21:59 UTC

**Comment by schrum2** [comment] 2016-05-13 05:39
Fixed by recent changes to NNTorusPredPreyController. This agent was not getting network inputs correctly, which was causing a NullPointerException. Basically, the agent was always sensing predators, even when it should have been sensing prey ... forgotten to generalize this code when generalizing the other code associated with this domain.

**Closed as completed by schrum2** 2016-05-13 05:39 UTC

**Comment by schrum2** [comment] 2016-05-13 05:41
Be sure to look at the commit I made that fixed this issue so you can see
what the problem is. Mainly need to look at NNTorusPredPreyController. Be
sure to update comments for this class when doing your new comments.

On Thu, May 12, 2016 at 4:59 PM, Rollinsa notifications@github.com wrote:

> Assigned #48 https://github.com/schrum2/MM-NEATv2/issues/48 to @schrum2
> https://github.com/schrum2.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/schrum2/MM-NEATv2/issues/48#event-659232564

## 

Jacob Schrum, Ph.D.
Assistant Professor of Computer Science
Department of Mathematics and Computer Science
Southwestern University
1001 E. University Ave.
Georgetown, TX 78626

Office: Mood-Bridwell Hall 141
Mail: SU Box 7341
Off-Campus Phone: (512) 863-1712
On-Campus Extension: x1712
E-mail: schrum2@southwestern.edu
WWW: http://southwestern.edu/~schrum2
